//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.Activities1 = new HashSet<Activity>();
            this.ActivityNotifications = new HashSet<ActivityNotification>();
            this.StockRequests = new HashSet<StockRequest>();
            this.Activities11 = new HashSet<Activity>();
            this.ActivitiesLogs = new HashSet<ActivitiesLog>();
        }
    
        public string TaskId { get; set; }
        public string Client_Id { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public int Category_Id { get; set; }
        public int SubCategory_Id { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public int Priority { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime EDOC { get; set; }
        public string CreatedBy { get; set; }
        public string TaskOwner { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string ParentTask_Id { get; set; }
        public string Status { get; set; }
        public string TaskType { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<int> Project_Id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities1 { get; set; }
        public virtual Activity Activity1 { get; set; }
        public virtual Category Category { get; set; }
        public virtual Department Department { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityNotification> ActivityNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockRequest> StockRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities11 { get; set; }
        public virtual Activity Activity2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivitiesLog> ActivitiesLogs { get; set; }
    }
}
