//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivitiesLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivitiesLog()
        {
            this.ActivityAttachments = new HashSet<ActivityAttachment>();
        }
    
        public int Id { get; set; }
        public string TaskId { get; set; }
        public System.DateTime TaskDate { get; set; }
        public string AssignedTo { get; set; }
        public string AssignedBy { get; set; }
        public Nullable<int> BudgetedHours { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> HoursWorked { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public Nullable<int> QuantityWorked { get; set; }
        public Nullable<int> Points { get; set; }
    
        public virtual Activity Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityAttachment> ActivityAttachments { get; set; }
    }
}
