//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovedInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApprovedInvoice()
        {
            this.ApprovedInvoiceServices = new HashSet<ApprovedInvoiceService>();
        }
    
        public string Id { get; set; }
        public int Client_Id { get; set; }
        public string CompanyAddress { get; set; }
        public string ClientAddress { get; set; }
        public string CurrencyType { get; set; }
        public decimal CurrentBillAmount { get; set; }
        public Nullable<decimal> TotalDueAmount { get; set; }
        public Nullable<decimal> TotalInvoiceAmount { get; set; }
        public int InvoiceCreatedBy { get; set; }
        public Nullable<System.DateTime> InvoiceCreatedDate { get; set; }
        public Nullable<int> InvoiceApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Status { get; set; }
        public string InvoiceURL { get; set; }
        public string Description { get; set; }
        public string InvoiceMonth { get; set; }
        public int InvoiceYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovedInvoiceService> ApprovedInvoiceServices { get; set; }
    }
}
