//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientReceivable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientReceivable()
        {
            this.ApprovedInvoiceServices = new HashSet<ApprovedInvoiceService>();
            this.ClientReceivableServices = new HashSet<ClientReceivableService>();
            this.InvoiceServices = new HashSet<InvoiceService>();
        }
    
        public int PaymentId { get; set; }
        public int Client_Id { get; set; }
        public string Currency { get; set; }
        public decimal AmountPaid { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string Description { get; set; }
        public string ScannedDocument { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovedInvoiceService> ApprovedInvoiceServices { get; set; }
        public virtual ClientReceivable ClientReceivables1 { get; set; }
        public virtual ClientReceivable ClientReceivable1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientReceivableService> ClientReceivableServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceService> InvoiceServices { get; set; }
    }
}
