//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultAllocation
    {
        public int Id { get; set; }
        public string JobLevel { get; set; }
        public decimal Accuracy { get; set; }
        public int Pages { get; set; }
        public int Client_Id { get; set; }
        public int Doctor_Id { get; set; }
        public int Employee_Id { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
