//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryChallan
    {
        public int Id { get; set; }
        public string CustomerId { get; set; }
        public string ChallanNumber { get; set; }
        public string ReferenceNumber { get; set; }
        public System.DateTime ChallanDate { get; set; }
        public string CustomerNotes { get; set; }
        public string TermsAndConditions { get; set; }
        public string ChallanType { get; set; }
    }
}
