//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorGroupEmployee
    {
        public int DoctorGroup_Id { get; set; }
        public int Employee_Id { get; set; }
    
        public virtual DoctorGroup DoctorGroup { get; set; }
    }
}
