//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePayscale
    {
        public int Id { get; set; }
        public int Gross { get; set; }
        public string BankName { get; set; }
        public string BankAccNo { get; set; }
        public string BankBranch { get; set; }
        public string BankAccName { get; set; }
        public Nullable<int> Emp_Id { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
