//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceService
    {
        public int Id { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public int ClientId { get; set; }
        public string InvoiceId { get; set; }
        public int ServiceId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public int TotalLines { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public Nullable<System.DateTime> AmountPaidDate { get; set; }
    
        public virtual ClientReceivable ClientReceivable { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
