//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Id { get; set; }
        public int ItemModelId { get; set; }
        public string SerialNumber { get; set; }
        public string BatchNumber { get; set; }
        public string SupplierId { get; set; }
        public int StockLocationId { get; set; }
        public string HardwareVersion { get; set; }
        public string MACAddress { get; set; }
        public Nullable<int> Warrenty { get; set; }
        public decimal CostPrice { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal MRP { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public bool IsAvailable { get; set; }
        public string BillNumber { get; set; }
        public string DeliveryChallanNumber { get; set; }
        public string InwardNumber { get; set; }
        public string PONumber { get; set; }
        public System.DateTime StockInDate { get; set; }
        public string StockReceiverUserId { get; set; }
        public Nullable<System.DateTime> ManufacturedDate { get; set; }
        public decimal MinimumSP { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public string WarrentyPeriod { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<System.DateTime> StockOutDate { get; set; }
    
        public virtual OrgansationLocation OrgansationLocation { get; set; }
        public virtual ItemsMaster ItemsMaster { get; set; }
    }
}
