//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsBillMapping
    {
        public int Id { get; set; }
        public Nullable<int> BillId { get; set; }
        public int ModelId { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public decimal PricePerUnit { get; set; }
        public string Description { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual ItemsMaster ItemsMaster { get; set; }
    }
}
