//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPrice
    {
        public int Id { get; set; }
        public int ItemModelId { get; set; }
        public System.DateTime FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public decimal SellingPrice { get; set; }
        public Nullable<decimal> DealerPrice { get; set; }
        public Nullable<decimal> DistributorPrice { get; set; }
    
        public virtual ItemsMaster ItemsMaster { get; set; }
    }
}
