//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opportunity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Opportunity()
        {
            this.OpportunitiesLogs = new HashSet<OpportunitiesLog>();
            this.OpportunityCategoryMappings = new HashSet<OpportunityCategoryMapping>();
            this.OpportunityContactMappings = new HashSet<OpportunityContactMapping>();
            this.StockRequests = new HashSet<StockRequest>();
        }
    
        public int Id { get; set; }
        public string OpportunityName { get; set; }
        public string Client_Id { get; set; }
        public string RefferedBy { get; set; }
        public Nullable<System.DateTime> EDOC { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string TaskOwner { get; set; }
        public string AssignedTo { get; set; }
        public string Description { get; set; }
        public int Org_Id { get; set; }
        public Nullable<System.DateTime> EDOS { get; set; }
        public Nullable<int> Location_Id { get; set; }
        public Nullable<System.DateTime> ActualCompletedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<System.DateTime> FollowUpOn { get; set; }
    
        public virtual ClientLocation ClientLocation { get; set; }
        public virtual Organisation Organisation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpportunitiesLog> OpportunitiesLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpportunityCategoryMapping> OpportunityCategoryMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpportunityContactMapping> OpportunityContactMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockRequest> StockRequests { get; set; }
    }
}
