//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpportunitiesLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OpportunitiesLog()
        {
            this.OpportunityAttachments = new HashSet<OpportunityAttachment>();
        }
    
        public int Id { get; set; }
        public int OpportunityId { get; set; }
        public string CreatedBy { get; set; }
        public string AssignedTo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
    
        public virtual Opportunity Opportunity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpportunityAttachment> OpportunityAttachments { get; set; }
    }
}
