//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POItemsMapping
    {
        public int Id { get; set; }
        public int POId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> CostPricePerUnit { get; set; }
    
        public virtual ItemsMaster ItemsMaster { get; set; }
        public virtual PuchaseOrder PuchaseOrder { get; set; }
    }
}
