//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockRequestMapping
    {
        public int Id { get; set; }
        public int StockReqId { get; set; }
        public int ItemId { get; set; }
        public int Quanitity { get; set; }
    
        public virtual ItemsMaster ItemsMaster { get; set; }
        public virtual StockRequest StockRequest { get; set; }
    }
}
