//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOut
    {
        public int Id { get; set; }
        public int SOId { get; set; }
        public System.DateTime StockOutDate { get; set; }
        public string StockHolderId { get; set; }
        public Nullable<int> StockReqId { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual SalesOrder SalesOrder { get; set; }
        public virtual StockRequest StockRequest { get; set; }
    }
}
