//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public string item_id { get; set; }
        public string item_name { get; set; }
        public string unit { get; set; }
        public string sku { get; set; }
        public Nullable<int> quantity_purchased { get; set; }
        public Nullable<int> quantity_sold { get; set; }
        public Nullable<int> quantity_ordered { get; set; }
        public Nullable<int> quantity_demanded { get; set; }
        public Nullable<int> quantity_available { get; set; }
        public Nullable<int> quantity_available_for_sale { get; set; }
        public Nullable<int> reorder_level { get; set; }
        public string Status { get; set; }
    }
}
