//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockRequest()
        {
            this.StockOuts = new HashSet<StockOut>();
            this.StockRequestMappings = new HashSet<StockRequestMapping>();
        }
    
        public int Id { get; set; }
        public string Client { get; set; }
        public int Project { get; set; }
        public System.DateTime ExpectedStockDate { get; set; }
        public string Notes { get; set; }
        public string Employee { get; set; }
        public string Status { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string TaskId { get; set; }
        public string ApprovedBy { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Opportunity Opportunity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockOut> StockOuts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockRequestMapping> StockRequestMappings { get; set; }
    }
}
